### ISSUE TITLE
No Such method Logger class

### ISSUE THREAD

**Issue by behera786** [mwdb/OA2C#1]
Hi 
i am getting java.lang.NosuchMethodError:org.apache.log4j.Logger.log(Ljava/lang/String) error.i added all required jar . 
could anybody tell me why i am getting this error.

![image001](https://user-images.githubusercontent.com/20984261/44296178-b0efb280-a2d6-11e8-9f60-11051bdc5961.png)

**Comment by Vest** [comment]
It is not the advertisement, but I kindly ask you to take my [fork](https://github.com/Vest/OA2C) and try to compile it either from Eclipse, or use Maven:
`mvn test`
